/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface DeployviewDashboard {
    }
    interface UiVerwaltung {
        "name": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDeployviewDashboardElement extends Components.DeployviewDashboard, HTMLStencilElement {
    }
    var HTMLDeployviewDashboardElement: {
        prototype: HTMLDeployviewDashboardElement;
        new (): HTMLDeployviewDashboardElement;
    };
    interface HTMLUiVerwaltungElement extends Components.UiVerwaltung, HTMLStencilElement {
    }
    var HTMLUiVerwaltungElement: {
        prototype: HTMLUiVerwaltungElement;
        new (): HTMLUiVerwaltungElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "deployview-dashboard": HTMLDeployviewDashboardElement;
        "ui-verwaltung": HTMLUiVerwaltungElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DeployviewDashboard {
    }
    interface UiVerwaltung {
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "deployview-dashboard": DeployviewDashboard;
        "ui-verwaltung": UiVerwaltung;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "deployview-dashboard": LocalJSX.DeployviewDashboard & JSXBase.HTMLAttributes<HTMLDeployviewDashboardElement>;
            "ui-verwaltung": LocalJSX.UiVerwaltung & JSXBase.HTMLAttributes<HTMLUiVerwaltungElement>;
        }
    }
}
