/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeployviewDashboard {
    }
    interface DeployviewRoot {
    }
    interface DeployviewVerwaltung {
        "name": string;
    }
}
declare global {
    interface HTMLDeployviewDashboardElement extends Components.DeployviewDashboard, HTMLStencilElement {
    }
    var HTMLDeployviewDashboardElement: {
        prototype: HTMLDeployviewDashboardElement;
        new (): HTMLDeployviewDashboardElement;
    };
    interface HTMLDeployviewRootElement extends Components.DeployviewRoot, HTMLStencilElement {
    }
    var HTMLDeployviewRootElement: {
        prototype: HTMLDeployviewRootElement;
        new (): HTMLDeployviewRootElement;
    };
    interface HTMLDeployviewVerwaltungElement extends Components.DeployviewVerwaltung, HTMLStencilElement {
    }
    var HTMLDeployviewVerwaltungElement: {
        prototype: HTMLDeployviewVerwaltungElement;
        new (): HTMLDeployviewVerwaltungElement;
    };
    interface HTMLElementTagNameMap {
        "deployview-dashboard": HTMLDeployviewDashboardElement;
        "deployview-root": HTMLDeployviewRootElement;
        "deployview-verwaltung": HTMLDeployviewVerwaltungElement;
    }
}
declare namespace LocalJSX {
    interface DeployviewDashboard {
    }
    interface DeployviewRoot {
    }
    interface DeployviewVerwaltung {
        "name"?: string;
    }
    interface IntrinsicElements {
        "deployview-dashboard": DeployviewDashboard;
        "deployview-root": DeployviewRoot;
        "deployview-verwaltung": DeployviewVerwaltung;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deployview-dashboard": LocalJSX.DeployviewDashboard & JSXBase.HTMLAttributes<HTMLDeployviewDashboardElement>;
            "deployview-root": LocalJSX.DeployviewRoot & JSXBase.HTMLAttributes<HTMLDeployviewRootElement>;
            "deployview-verwaltung": LocalJSX.DeployviewVerwaltung & JSXBase.HTMLAttributes<HTMLDeployviewVerwaltungElement>;
        }
    }
}
